Site/urls.py
from django.contrib import admin
from django.template.defaulttags import url

from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('redoc/', get_schema_view(title="My API", description="API for all things …", version="1.0.0"),
                       name='redoc-schema'),
                  path('chat/', include('chat.urls')),
                  path('group/', include('sendmails.urls')),
                  re_path('api/auth/', include('djoser.urls')),
                  re_path(r'^auth/', include('djoser.urls.authtoken')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import models
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.apps import apps

class UserManager(BaseUserManager):
    use_in_migrations = True
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user( email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    SEX_CHOISE = [
        (1, 'Man'),
        (2,  'Woman')
    ]

    sex=models.PositiveIntegerField(verbose_name="sex", choices=SEX_CHOISE, blank=True, default=1)
    birth_date = models.DateField(verbose_name="birthday" , null=True, blank=True)



    email=models.EmailField(verbose_name="email", unique=True, error_messages={
            "unique": _("A user  with that email already exists."),
        },)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=False,
        validators=[username_validator],
        blank=True,
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    # objects = UserManager()







class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    description = models.TextField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_order =  models.DateTimeField(auto_now_add=True)
    complete =models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems =self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item  in orderitems])
        return total

    @property
    def shipping(self):
        shipping =False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False :
                shipping = True
        return  shipping


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total

    # def __str__(self):
    #     return f'{self.email, self.username, self.}'


class ShippingAddress(models.Model):
    customer = models.ForeignKey(User,  on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=12, null=True)

    def __str__(self):
        return self.address

templates/apps/aboutpage.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}

    profile

{% endblock %}


{% block content %}
    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>
            <div class="col-md-8  rounded justify-content-center  ">
                <div class="card card-body " style="background-color:#e3ffff">
                    {#                    <form name="Sign_in" method="post">#}
                    {% csrf_token %}
                    <h1 style="text-align: center">About us  </h1>
                    <div class="mb-md-2 d-grid gap-3  ">
                        <div class="mb-md-2 d-grid gap-3 text-center " >
                            <p> This site is a project for the course of web programming</p>
                            <p> The site is a shop for buying products</p>
                            <p> Your can choose your product and buy it.</p>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/cart.html
{% extends 'apps/index.html' %}
{% load static %}






{% block products %}
    <br>
    <div class="container-md p-1 card ">
        <div class="row">
            <div class=" col col-md-4 ">
                <a class="btn btn-outline-primary " href="{% url 'main' %}"> <- Back to shoping </a>
            </div>
            <div class="col-auto ">
                <h2>Cart</h2>
            </div>
        </div>

        <hr>
        <table class="table">
            <tr>
                <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                <th><h5>Total: <strong>{{ order.get_cart_total }}</strong></h5></th>
                <th><a style="float: right;margin: 5px" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
                </th>
            </tr>
        </table>
    </div>
    <br>
    <br>
    <div class="col-auto p-1 card">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Item</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
                <th scope="col">Total</th>
            </tr>
            </thead>
            <tbody>
            {% for  elem in items %}
                <tr>
                    <th scope="row"><img src="{{ elem.product.image.url }}" style="width: 100px ; height: 100px"></th>
                    <td><p class="px-lg-2">{{ elem.product.name }}</p></td>
                    <td><p class="px-lg-2">{{ elem.product.price }}</p></td>
                    <td>
                        <p class="px-sm-2">{{ elem.quantity }}
                            <button class=" btn  update-cart  " data-product='{{ elem.product.id }}' data-action='add'>
                                +
                            </button>
                            <button class=" btn update-cart" data-product='{{ elem.product.id }}' data-action='remove'>
                                -
                            </button>
                        </p>

                    </td>
                    <td><p class="px-lg-2">{{ elem.get_total }}</p></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <script type="text/javascript">
        var updateBtns = document.getElementsByClassName('update-cart')
        var user = '{{ request.user }}'
        for (var i = 0; i < updateBtns.length; i++) {
            updateBtns[i].addEventListener('click', function () {
                var productId = this.dataset.product
                var action = this.dataset.action
                console.log('productId:', productId, 'action:', action)
                console.log('User:', user)

                if (user === 'AnonymousUser') {
                    console.log("User not is authentification")
                } else {
                    updateUserOrder(productId, action)

                }


                function updateUserOrder(productId, action) {
                    console.log("User is authentificated , sending data...")

                    var url = '/update_item/'

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': csrftoken,

                        },
                        body: JSON.stringify({'productId': productId, 'action': action})

                    })
                        .then((response) => {
                            return response.json()
                        })

                        .then((data) => {
                            location.reload()
                            {#console.log('data:', data )#}
                        })
                }
            })
        }

    </script>
{% endblock %}

templates/apps/checkout.html
{% extends 'apps/index.html' %}
{% load bootstrap5 %}





{% block products %}
    <br>
    <div class="container-md p-1 card ">
        <div class="row">
            <div class=" col col-md-5">
            </div>
            <div class="col-auto ">
                <h2>Checkout</h2>
            </div>
        </div>
    </div>
    <br>
    <div class="col p-1 ">
        <div class="row">
            <div class="col-auto col-md-6  px-2  card">
                <div id="shipping-info">
                    <div class="text-center"><p><h4>Delivery address</h4></p> </div>

                    <form method="post" name="checkout_id">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <div class="d-grid gap-2 py-2">
                            <button type="submit" class="btn btn-primary  bt btn-block"> Submit</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-auto col-md-6 px-2 card">

                <div class="row  p-2">
                    <div class="col-md-5 p-3">
                        <a class="btn btn-outline-primary" href="{% url 'cart' %}"> <- Back to Cart</a>
                    </div>
                    <div class="col-md-4">
                        <p>
                        <h2><strong>Cart</strong></h2></p>
                    </div>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Item</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for  elem in items %}
                        <tr>
                            <th scope="row"><img src="{{ elem.product.image.url }}"
                                                 style="width: 50px ; height: 50px">
                            </th>
                            <td><p class="px-lg-2">{{ elem.product.name }}</p></td>
                            <td><p class="px-lg-2">{{ elem.product.price }}</p></td>
                            <td><p class="px-lg-2">{{ elem.quantity }}</p></td>
                            <td><p class="px-lg-2">{{ elem.get_total }}</p></td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
                <div class="row-auto">
                    <table class="table">
                        <tr>
                            <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                            <th><h5>Total: <strong>{{ order.get_cart_total }}</strong></h5></th>
                            {#                            <th><a style="float: right;margin: 5px" class="btn btn-success"#}
                            {#                                   href="{% url 'cart' %}">Back to Cart </a></th>#}
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        var shipping = '{{ order.shipping }}'

        if (shipping === 'false') {
            document.getElementById('shipping-info').innerHTML = ''
        }

    </script>
{% endblock %}
</body>
</html>

templates/apps/editprofile.html
{% extends 'base/base.html' %}
{% load bootstrap5 %}

{% block title %}

    Update Profile

{% endblock %}


{% block content %}
    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>

            <div class="col-md-3  rounded justify-content-center  ">
                <div class="card card-body" style="background-color:#e3ffff">
                    <form name="Sign_up" method="post" >
                        {% csrf_token %}
                        <h1 style="text-align: center">Update Profile </h1>

                        <div class="mb-md-3 d-grid gap-2 ">
                            {% bootstrap_form  form %}
                        </div>
                        <span> {{ error }}</span>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary  bt btn-block"> Save</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/groups.html
{% extends 'base/base.html' %}

{% block title %}

Group
{% endblock %}


{% block content %}
    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>

            <div class="col-md-3  rounded justify-content-center  ">
                <div class="card card-body" style="background-color:#e3ffff">
                    <form name="Sign_in" method="post">
                        {% csrf_token %}
                        <div class="mb-md-3 d-grid gap-2 ">
                            {{ form }}
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary  bt btn-block">Save</button>
                        </div>
                                                <p class="text-center">Create notification for group <a href="{% url 'notification' %}">Create</a></p>
                        {#                        <p class="text-center">Don't have a account? <a href="{% url 'signup' %}">Sing Up</a></p>#}
                    </form>

{#                    <h4>Groups:</h4>#}
{#                    <ul>#}
{#                        {% for group in groups %}#}
{#                            <li>{{ group.name }}</li>#}
{#                            <ul>#}
{#                                {% for user in group.user_set.all %}#}
{#                                    <li>{{ user.username }}</li>#}
{#                                {% endfor %}#}
{#                            </ul>#}
{#                        {% endfor %}#}
{#                    </ul>#}
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/index.html
{% extends 'base/base.html' %}

{% block title %}
    index
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto  col-md-2 px-0 bg-white">
                <div class="d-flex flex-column  px-2 pt-2 ">
{#                    <div class="btn-group-vertical" role="group" aria-label="Basic mixed styles example">#}
{#                        <a href="" type="button" id="all_task" class="btn btn-secondary ">buttom1</a>#}
{#                        <a href="" type="button" id="create_task" class="btn btn-secondary">buttom2</a>#}
{#                    </div>#}
                </div>

            </div>
            <div class="col-auto col-md-8">
                {% block view %}
                {% endblock %}
                {% block chat %}
                {% endblock %}
                {% block products %}
                {% endblock %}

            </div>
            <div class="col-auto col-md-2">

            </div>

        </div>

    </div>











{% endblock %}

templates/apps/login.html
{% extends 'base/base.html' %}

{% block title %}

    Login

{% endblock %}


{% block content %}
    {#    <div class="center">#}
    {#	  <form method="post" class="card" novalidate>#}
    {#	  	{% csrf_token %}#}
    {#	    <h2 class="text-center">Log in to your account</h2>#}
    {#		{% for field in form %}#}
    {#	    		{{ field.label_tag }} #}
    {#	        	{{ field }}#}
    {#	        	{% if field.errors %}#}
    {#	        		<small>{{ field.errors|striptags }}</small> #}
    {#	        	{% endif %}#}
    {#		{% endfor %}#}
    {#		#}
    {#		<input type="submit" value="Login" class="btn btn-primary full-width">#}
    {#		<hr>#}
    {#		<p class="text-center">Forgot your password <a href="#">Reset Password</a></p>#}
    {#		<p class="text-center">Don't have a account? <a href="#">Join Now</a></p>#}
    {#	</form>#}
    {#</div>#}

    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>

            <div class="col-md-3  rounded justify-content-center  ">
                <div class="card card-body" style="background-color:#e3ffff">
                    <form name="Sign_in" method="post" >
                        {% csrf_token %}
                        <h1 style="text-align: center">Sign in </h1>

                        <div class="mb-md-3 d-grid gap-2 ">
                            {{ form  }}
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary  bt btn-block">Login</button>
                        </div>
{#                        <p class="text-center">Forgot your password <a href="#">Reset Password</a></p>#}
                        <p class="text-center">Don't have a account? <a href="{% url 'signup' %}">Sing Up</a></p>
                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/notification.html
{% extends 'base/base.html' %}

{% block title %}

Group
{% endblock %}


{% block content %}
    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>

            <div class="col-md-3  rounded justify-content-center  ">
                <div class="card card-body" style="background-color:#e3ffff">
                    <form name="Sign_in" method="post">
                        {% csrf_token %}
                        <div class="mb-md-3 d-grid gap-2 ">
                            {{ form }}
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary  bt btn-block">Save</button>
                        </div>
{#                                                <p class="text-center">Create notification for group <a href="{% url 'group/notifications' %}">Create</a></p>#}
                        {#                        <p class="text-center">Don't have a account? <a href="{% url 'signup' %}">Sing Up</a></p>#}
                    </form>

{#                    <h4>Groups:</h4>#}
{#                    <ul>#}
{#                        {% for group in groups %}#}
{#                            <li>{{ group.name }}</li>#}
{#                            <ul>#}
{#                                {% for user in group.user_set.all %}#}
{#                                    <li>{{ user.username }}</li>#}
{#                                {% endfor %}#}
{#                            </ul>#}
{#                        {% endfor %}#}
{#                    </ul>#}
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}

    profile

{% endblock %}


{% block content %}
    <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>
            <div class="col-md-4  rounded justify-content-center  ">
                <div class="card card-body " style="background-color:#e3ffff">
                    {#                    <form name="Sign_in" method="post">#}
                    {% csrf_token %}
                    <h1 style="text-align: center">profile </h1>
                    <div class="mb-md-2 d-grid gap-3 ">
                        <table class="table ">
                            {% for el in profile %}
                                <tr>
                                    <th scope="row">Name</th>
                                    <td>{{ el.username }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Email</th>
                                    <td>{{ el.email }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Birthday</th>
                                    <td>{{ el.birth_date }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Sex</th>
                                    <td>{{ el.get_sex_display }}</td>
                                </tr>

                                </table>
                                <a type="button" class="btn btn-secondary" href="{% url 'edit' pk=el.id %}">
                                    <img src="{% static 'image/apps/pen.svg' %}" width="16" height="16">

                                    Edit
                                </a>
                            {% endfor %}
                    </div>

                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/registration.html
{% extends 'base/base.html' %}
{% load bootstrap5 %}

{% block title %}

    Login

{% endblock %}


{% block content %}
     <div class="container-fluid ">
        <div class="row" style="margin: 1%"></div>
        <div class="row">
            <div class="col"></div>

            <div class="col-md-3  rounded justify-content-center  ">
                <div class="card card-body" style="background-color:#e3ffff">
                    <form name="Sign_up" method="post" >
                        {% csrf_token %}
                        <h1 style="text-align: center">Sign Up </h1>

                        <div class="mb-md-3 d-grid gap-2 ">
{#                             {% for fields in form %}#}
{#                                {{ fields}}#}
{#                              {% endfor %}#}
                            {% bootstrap_form  form %}
                        </div>
                        <span> {{ error }}</span>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary  bt btn-block"> Submit</button>

                        </div>
{#                        <p class="text-center">Forgot your password <a href="#">Reset Password</a></p>#}
{#                        <p class="text-center">Don't have a account? <a href="#">Join Now</a></p>#}

                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

templates/apps/store.html
{% extends 'apps/index.html' %}
{% load static %}


{% block products %}



    <div class="col-auto px-2 px-lg-2 m-2">
        <h3 class="text-center">Products</h3>
        {% for elem in obj %}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class=" col col-md-3 px-1">
                            {#                                        <img src="">#}
                            <img class="img-thumbnail" src="{{ elem.image.url }}">
                        </div>
                        <div class="col-auto col-md-6 px-2 ">

                            <p class="text" >Name:{{ elem.name }}</p>
                            <p class="text"> Price: {{ elem.price }}</p>
                            <p class="text">Description {{ elem.description }}</p>

                        </div>
                        <div class=" col px-1">
                            <div class="row row-cols-md-2">
                                <button class="btn-outline-success btn update-cart" data-product="{{ elem.id }}"
                                        data-action="add" href="">Add to cart
                                </button>
                                <br>
                            </div>
                            {#                            <div class="row row-cols-md-3 px-1">#}
                            <div class="row row-cols-md-2">
                                <a  class="btn-outline-secondary btn" href="{% url 'chat-index' %}">Discuss
                                </a>
                            </div>

                            {#                            <button class="btn-outline-success btn update-cart" data-product="{{ elem.id }}"#}
                            {#                                    data-action="add" href="">Add to cart#}
                            {#                            </button>#}
                            {#                            <a class="btn-outline-secondary btn" href="">View </a>#}

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <script src="{% static 'index.js' %}"></script>
    </div>


    <script type="text/javascript">
        var updateBtns = document.getElementsByClassName('update-cart')
        var user = '{{ request.user }}'
        for (var i = 0; i < updateBtns.length; i++) {
            updateBtns[i].addEventListener('click', function () {
                var productId = this.dataset.product
                var action = this.dataset.action
                console.log('productId:', productId, 'action:', action)
                console.log('User:', user)

                if (user === 'AnonymousUser') {
                    console.log("User not is authentification")
                } else {
                    updateUserOrder(productId, action)

                }


                function updateUserOrder(productId, action) {
                    console.log("User is authentificated , sending data...")

                    var url = '/update_item/'

                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': csrftoken,


                        },
                        body: JSON.stringify({'productId': productId, 'action': action})

                    })
                        .then((response) => {
                            return response.json()
                        })

                        .then((data) => {
                            location.reload()
                            {#console.log('data:', data )#}
                        })
                }
            })
        }

    </script>


{% endblock %}

templates/apps/users_online.html
{% extends 'apps/index.html' %}
{% load static %}
{% block chat %}
    <div class="container-fluid">
    <br>
    <div class="col-auto p-1 card px-2">
                    <label for="UserOnline" style="position: center;" >Active Users</label>
                    <select multiple class="form-control" id="UserOnline">
                        {% for user in users %}
                            <option>{{ user }}</option>
                        {% endfor %}
                    </select>
                </div>
    </div>

{% endblock %}